#!/bin/sh

die() {
    test "$1" && echo "$1" >&2
    exit 1
}

me="$0"
here=$(pwd)

ci_repo="$1"

cd "$ci_repo/guests/" >/dev/null 2>&1 || {
    die "Usage: $me path/to/libvirt-jenkins-ci.git"
}

for host in $(./lcitool -a hosts)
do
    projects="libvirt"
    dockerfile="$here/buildenv-${host#libvirt-}.Dockerfile"

    case "$host" in
        libvirt-fedora-rawhide) projects="libvirt,libvirt+mingw" ;;
        libvirt-freebsd-*)      continue ;;
    esac

    ./lcitool -a dockerfile -h "$host" -p "$projects" >"$dockerfile" || {
        die "$me: Failed to refresh Dockerfile for $host"
    }
done
